<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VMWV.Infrastructure.Windows/VMWV.Infrastructure.Windows.csproj" />
    <Compile Include="../VMWV.App/Models/DiagnosticLogEntry.cs" Link="DiagnosticLogEntry.cs" />
  </ItemGroup>
</Project>
